---
version: 2
updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "ci"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: nuget
    commit-message:
      prefix: "deps"
    directory: "/src"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "AwesomeAssertions"
        versions: [">=9.0.0, <10.0.0"]