# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  solutionName: FluentAssertions.ArgumentMatchers.Moq
  projects: '**/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Required for NuGetCommand@2
- task: NuGetToolInstaller@1

# Required for DotNetCoreCLI@2
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

- task: DotNetCoreCLI@2
  displayName: "NuGet Restore"
  inputs:
    command: restore
    projects: '$(projects)'

- task: DotNetCoreCLI@2
  displayName: "Build Solution"
  inputs:
    command: build
    projects: '$(projects)'
    arguments: '--configuration $(buildConfiguration)'

#- task: NuGetCommand@2
#  displayName: "NuGet Restore"
#  inputs:
#    restoreSolution: '$(solution)'

#- task: VSBuild@1
#  displayName: "Build Solution"
#  inputs:
#    solution: '$(solution)'
#    platform: '$(buildPlatform)'
#    configuration: '$(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --logger trx'

- task: CopyFiles@2
  displayName: 'Copy NuGet Package'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/$(solutionName)'
    Contents: '**\*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Package'
    FlattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    artifactName: $(solutionName)
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Package'