# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

#- task: SonarQubePrepare@4
#  inputs:
#    SonarQube: 'SonarQube'
#    scannerMode: 'MSBuild'
#    projectKey: '
#    projectName: 'FluentAssertions.ArgumentMatchers.Moq'
#    projectVersion: '$(AssemblyVersion)'
#    extraProperties: sonar.branch.name=$(Build.SourceBranchName)

- task: SonarQubePrepare@4
  inputs:
    SonarQube: 'SonarQube'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'FluentAssertions.ArgumentMatchers.Moq'
    cliProjectName: 'FluentAssertions.ArgumentMatchers.Moq'
    cliSources: '.''

- task: DotNetCoreCLI@2
  displayName: "NuGet Restore"
  inputs:
    command: restore
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: "Build Solution"
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: 'Run Tests'
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --logger trx'

- task: SonarQubeAnalyze@4

- task: SonarQubePublish@4
  inputs:
    pollingTimeoutSec: '300'

- task: CopyFiles@2
  displayName: 'Copy NuGet Package'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/Package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    artifactName: 'FluentAssertions.ArgumentMatchers.Moq'
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Package'