# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.401'

- task: NuGetCommand@2
  displayName: "NuGet Restore"
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
- script: dotnet test
  displayName: 'Run .NET Core Tests'

- task: PublishTestResults@2 # To publish test run with 'dotnet test'

- task: NuGetCommand@2
  displayName: "NuGet Pack"
  inputs:
    command: pack
    packagesToPack: '**/*.csproj'	

- task: NuGetCommand@2
  displayName: 'NuGet Push'
  inputs:
    command: push
    publishVstsFeed: 'Test'
    allowPackageConflicts: true