name: pull-request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  contents: read

jobs:
  build-and-test:
    uses: ./.github/workflows/callable-build-and-test.yml
