name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build-and-test:
    needs: release-please
    if: needs.release-please.outputs.release-created == 'true'
    uses: ./.github/workflows/callable-build-and-test.yml
