name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release-please.outputs.releases_created }}
    steps:
      - id: release-please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

  build-and-test:
    needs: release-please
    if: needs.release-please.outputs.release-created == 'true'
    uses: ./.github/workflows/callable-build-and-test.yml

  publish-nuget:
    needs:
      - release-please
      - build-and-test
    if: needs.release-please.outputs.release-created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and pack
        run: |
          dotnet pack ./src/AwesomeAssertions.ArgumentMatchers.Moq.sln \
          --configuration Release \
          -o ./artifacts \
          /p:PackageVersion=${{ github.ref_name }}

      - name: Publish to NuGet
        run: |
          dotnet nuget push "./artifacts/*.nupkg" ./src/AwesomeAssertions.ArgumentMatchers.Moq.sln \
          --api-key ${{ secrets.NUGET_API_KEY }} \
          --source https://api.nuget.org/v3/index.json
